### ISSUE TITLE
[PS] Errors are not being shown correctly in checkout

### ISSUE THREAD

**Issue by andreasantillana** [conekta/conektaprestashop#27]
Un request para crear la orden + cargo es de la siguiente manera:
```
::1 - - [28/Dec/2016:18:48:04 -0600] "POST /prestashop/modules/conektaprestashop/charge.php HTTP/1.1" 302 383086
::1 - - [28/Dec/2016:18:48:05 -0600] "GET /prestashop/order?step=3&conekta_error=1&message=shipping_lines%20tiene%20un%20tipo%20inv%C3%A1lido. HTTP/1.1" 200 7984
```

Regresa un error, pero la  UI no lo está parseando correctamente:
(esto sucede para cualquier forma de pago)
![image](https://cloud.githubusercontent.com/assets/5167417/21534737/dcab5f00-cd30-11e6-97d8-34210bc57df4.png)

**Comment by fruizg0302** [comment]
This was corrected :)
