### ISSUE TITLE
[PS] Agregar campos a la  forma (external number, internal number)

### ISSUE THREAD

**Issue by andreasantillana** [conekta/conektaprestashop#28]
Para poder agregar los campos de `external_number` e `internal_number` a la forma de la dirección, hay que hacer lo siguiente:
- override de clase `Address`
- override de controlador `AdminAddressesController`
- override de controlador `AddressController`
- crear template de Address que replique lo que ya existe y  agregar los campos
- En Localization > Countries agregar para cada país los campos para mostrar en la forma (esto lo tendría que hacer el usuario):
![image](https://cloud.githubusercontent.com/assets/5167417/21567164/7e39246c-ce6f-11e6-8c55-3445ff0c476c.png)

referencia: http://nemops.com/new-customer-address-fields-prestashop/#.WGZrMrYrLBI
https://www.prestashop.com/forums/topic/166078-solved-how-can-i-add-custom-fields-to-new-user-registration/

**Comment by fruizg0302** [comment]
This was not possible
