### ISSUE TITLE
Dudas instalación prestashop 1.7

### ISSUE THREAD

**Issue by gengiscb** [conekta/conektaprestashop#45]
Disculpa tengo una duda acerca del plugin, actualmente quiero usar la versión de prestashop 1.7 en especifico la versión 1.7.0.5, ustedes en su documentación dicen que solo soporta 1.6.1.11 o inferior pero sus capturas de pantallas son de la versión 1.7.0.3, el plugin se instala bien en la V1.7.0.5 configuro los parámetros guardo y todo bien pero no me sale en las opciones de pagos>métodos de pago y pues no lo puedo visualizar en la pasarela de pago. Mi duda es que si la versión del plugin conektaprestashop-2.0.3 tiene soporte para la versión 1.7 o tienen pensado en agregar soporte.

**Comment by Janee** [comment]
Hola @gengiscb 
Actualmente no tiene soporte la versión 1.7 pero en aproximadamente dos semanas lanzaremos un beta.
Con gusto te puedo añadir a lista de espera si enviar un correo a soporte@conekta.com

Saludos
