### ISSUE TITLE
[PS] Error Oxxo Pay

### ISSUE THREAD

**Issue by rogerlopz** [conekta/conektaprestashop#49]
Hola, tengo un error tanto en modo sandbox como en producción a la hora de recibir pagos con Oxxo Pay.

Cuando un usuario selecciona un producto y paga con oxxo pay le aparece su número de referencia pero jamás le llega a su correo un pdf con su numero de referencia, así como tampoco aparece en su página de perfil en la sección de historial de pedidos

En el backoffice, al acceder a su pedido muestra su numero de referencia (el que se usa para pagar en oxxo) como mensaje hacia el usuario. Ahi mismo, en el pedido aparece el siguiente error:

`Warning: The customer paid using Conekta and an error occured (check details at the bottom of this page)`

Cuando voy al fondo de la página simplemente no aparece nada y tampoco aparece algo en la consola de depuración.

Una vez hecho el pedido, al usuario le aparece eso:
<img width="1068" alt="captura de pantalla 2017-03-28 a la s 13 57 16" src="https://cloud.githubusercontent.com/assets/4995589/24427055/824934f4-13be-11e7-8d6e-adeba6af13fe.png">

En su página de pedidos le aparece esto:
<img width="1196" alt="captura de pantalla 2017-03-28 a la s 13 58 21" src="https://cloud.githubusercontent.com/assets/4995589/24427123/b1a6b654-13be-11e7-8947-fb57926dbf40.png">

En la página de pedido (backoffice) aparece esto: 
<img width="503" alt="captura de pantalla 2017-03-28 a la s 13 59 17" src="https://cloud.githubusercontent.com/assets/4995589/24428264/b83b1a38-13c2-11e7-8756-f77fd04aa639.png">

y esto:
<img width="709" alt="captura de pantalla 2017-03-28 a la s 14 00 04" src="https://cloud.githubusercontent.com/assets/4995589/24427172/e1224c5e-13be-11e7-8cf8-27c57685bb8c.png">

Pero en el fondo de la página no aparece nada.

Saludos.

**_Edit: añado dato técnicos de mi instancia de prestashop_**

**Información del servidor**
- Versión del servidor web LiteSpeed
- Versión de PHP 7.0.17
- Límite de memoria 768M
- Tiempo Máximo de ejecución 300

**CONFIGURACIÓN DE LA BASE DE DATOS**
- Versión de MySQL 5.6.23-cll-lve
- Prefijo de las tablas ps_
- Motor MySQL InnoDB
- Controlador MySQL DbPDO

**Versión de la tienda**
- Versión de PrestaShop 1.6.1.10

**CONFIGURACIÓN DE EMAIL**
- Utiliza la función email() de PHP

Como nota adicional me gustaría aclarar que el webhook me da una URL sin SSL (http) cuando toda mi tienda esta activada para funcionar con SSL (https), así que no sé si eso influya.

**Comment by KarlaRobinson** [comment]
Hola Roger,

(Estoy suponiendo que estas usando la version mas actual de nuestro plugin: v.2.0.5.)

Para poder mandar el correo de confirmación de pago, es necesario que configuras tu host en el admin de Prestashop. Este información se agrega en Parametros Avanzados >> Correo Electronico, y seleccionando:
 "Establecer mis propios parámetros SMTP. Sólo para usuarios AVANZADOS" 

Aquí, al ingresar los datos de tu host se debe de mandar el correo de confirmación. 

![image](https://cloud.githubusercontent.com/assets/20826318/24722610/fe1f763c-1a09-11e7-8de9-770932c674ce.png)
![image](https://cloud.githubusercontent.com/assets/20826318/24721836/2644d682-1a07-11e7-9705-3712a4f317ab.png)

Y en cuanto a tu otra duda del warning: Como se crea el order de forma exitosa debe ser un warning creado por Prestashop. Fijate en tus logs del admin de Conekta para checar que todo sea 200, en dev tools si te da algún error al completar el pago o si tienes alguna actualización pendiente en el admin de Prestashop.

O, si gustas que revisemos tu sitio, mandános un correo con tu la información a soporte@conekta.com!

Saludos,
Karla
