### ISSUE TITLE
Compatibilidad con prestashop 1.7

### ISSUE THREAD

**Issue by HektorCyC** [conekta/conektaprestashop#51]
Traté de instalar el plugin en la version mas nueva de prestashop (1.7) y no logré hacerlo funcionar.

**Comment by gengiscb** [comment]
Así es el plugin no funciona con la versión 1.7, a mi me comentaron que en febrero iba a salir la actualización para para la versión 1.7 y eso fue en enero ya estamos en Mayo y aún nada, así que mis clientes decidieron usar Stripe.

**Comment by mvalderrama** [comment]
Hola, también estoy trabajando con Prestashop, versión 1.7.1.2, cargo e instalo el módulo, configuro las llaves de prueba y lo habilito, pero no me aparece el método de pago en el checkout.
¿Será un problema de compatibilidad del módulo, o es un problema de configuración de mi parte?

**Comment by edenriquez** [comment]
Hola @HektorCyC , @mvalderrama  acabamos de sacar nuestra mas reciente version para prestashop 1.7 estamos en proceso de subir este plugin al marketplace de prestashop pero por lo pronto ya pueden utilizarlo si gustan instalarlo manualmente https://github.com/conekta/conekta_prestashop

**Comment by mvalderrama** [comment]
@eduardoconekta, muchas gracias.
Disculpa, el link que dejaste para descargar el módulo actualizado no funciona, y en el proyecto, el último commit que aparece es del 30 de junio, que es la versión que estuve probando previamente.

Serías tan amable de compartir de nuevo el link con el módulo actualizado con soporte a la versión 1.7 por favor.

Gracias

**Comment by edenriquez** [comment]
Una disculpa, no recordaba que ese repositorio es privado, a mas tardar el lunes gestionamos que quede publico, de igual forma estamos verificandolo en el marketplace de prestashop posiblemente ellos antes nos aprueben el plugin y se pueda descargar directo de PS, aun asi quedo en confirmarte cuando este listo 👍  @mvalderrama

**Comment by mvalderrama** [comment]
Muchas gracias @eduardoconekta, quedo a la espera de la publicación del módulo actualizado, saludos.

**Comment by edenriquez** [comment]
@mvalderrama que tal, una disculpa ya que esta demorando la revision de nuestro plugin hemos actualizado bastante el diseño para la version 1.7 y sigue en proceso de validación por parte de nuestro team para liberarlo por el repo y seguimos en proceso de subida en el marketplace, cualquier duda puedes contactarte conmigo eenriquez@conekta.com.

**Comment by edenriquez** [comment]
Release de compatibilidad con PS 1.7 https://github.com/conekta/conekta_prestashop

**Comment by Dayherrera** [comment]
Alguien me puede decir cual es la ruta del webhook ya que cuando lo instalo me deja el campo en blanco
trate de ponerle esto https://midominio/modules/conekta_prestashop/conekta_prestashop.php pero no me cambia el estado del pago en mi catalogo de pedidos.  Todo eso pasa cuando elijo oxxo pay y el otro  ploblema es que si eljo pago con tarjeta no tokeniza simplemente me recarga la pagina y mi carrito de compras se mantiene igual y tampoco se refleja el cargo en el panel de administración de conekta, cabe mencionar que el de oxxo pay si se refleja el cargo, pero no actualiza el estado en prestashop.

**Comment by ohlalo10** [comment]
Hola DayHerrera, me pasa exactamente lo mismo que a ti, tanto en pago con tarjetas como en oxxo pay, no actualiza el estado del panel de pedidos, pudiste resolverlo??

Tengo prestashop 1.7

Saludos

**Comment by edenriquez** [comment]
Hola @ohlalo10 y @Dayherrera si bajaron nuestro plugin de prestashop  desde marketplace les informo que en esa version desafortunadamente no pudimos acreditar el archivo de webhook como valido, las validaciones de marketplace no dejaron alojar este, sin embargo pueden copiar y pegar https://github.com/conekta/conektaprestashop/blob/master/notification.php ese archivo, internamente el plugin ya maneja el webhook unicamente falta ese archivo para que se actualicen las ordenes

**Comment by ohlalo10** [comment]
Hola eduardo, te comento que instale la versión  1.1.0, desde https://github.com/conekta/conekta_prestashop.git 

Si contiene el archivo notification.php , sin embargo para hacer la prueba con el que me pasaste lo remplace, pero continuo con el problema, no actualiza el ESTADO del pedido en el panel del Prestashop

Las pruebas las han realizado bajo alguna versión especifica?

Yo tengo instalado Prestashop 1.7.3.0

saludos

**Comment by Dayherrera** [comment]
@ohlalo10 No pude resolver el problema, estuve en constante comunicación con el equipo de prestashop durante un mes al final me recomendaron bajar de versión de prestashop a la 1.6.3 creo o bien que siguiera esperando por lo que decidí bajarme a esa versión. una vez tuve todo listo no me dieron el permiso para recibir pagos con tarjeta porque no tenia suficiente antigüedad en ventas en linea  por lo que decidí cambiar a openpay y regresar ala version 1.7.3 de prestashop  todo fue fácil el tramite y sencilla la instalación. Espero te sirva mi corta experiencia...

**Comment by ohlalo10** [comment]
Gracias Dayherrera, por compartir tu experiencia, oxxo pay con conektra me interesa, creo q es una muy buena opcion para los usuarios voy a intentar un poco mas, espero tenga arreglo, si embargo voy a probar con openpay, saludos

**Comment by Dayherrera** [comment]
@ohlalo10 de nada buena suerte y arriba me equivoque en el comentario con quien estuve en contacto via correo fue  con el equipo de desarrollo de conekta, te recomiendo que le escribas directamente a soporte@conekta.com quizás desde ahí te puedan asesorar de forma mas personalizada y para este tiempo quizás ya tengan una solución al problema que si mal no recuerdo me comentaron que era algo difícil...

**Comment by edenriquez** [comment]
@ohlalo10 debe ser la version mas reciente la que ocupaste, pero bueno voy a hacer las pruebas necesarias para poder solucionar el problema, @Dayherrera que problema tuviste especificamente ?, una disculpa por los inconvenientes, te recomendaria que hagas las pruebas no solo con openpay si no con todos quienes ofrezcan procesamiento de pagos, asi como tambien lo es conekta, hemos mejorado bastante nuestra aplicación desde hace unos meses, y personalmente he visto que nuestra proteccion antifraude es de las mejores del mercado, asi como la aceptación bancaria, oxxoPay y mas recientemente Oxxo Recurrente 👍 que son features que solo tenemos en conekta :)

**Comment by edenriquez** [comment]
@ohlalo10 listo, el nuevo código ya esta en el repositorio, para hacer la prueba, tendrías que desinstalar el plugin y borrar también el webhook desde tu admin de conekta

**Comment by ohlalo10** [comment]
Buenas Tardes @eduardoconekta  he probado el módulo con la actualización y te comento que ha funcionado correctamente con oxxo pay, ahora si actualiza el panel de pedidos de prestashop... 

Sin embargo, existe el mismo problema con el pago de tarjetas, al momento de  hacer el pago, hace  un postback y redirecciona a la pagina principal, y el carrito de compras se queda con los artículos previamente seleccionados.

Muchas gracias, saludos

**Comment by ohlalo10** [comment]
hola @Dayherrera gracias por el dato, te comento que esta ultima actualización que realizo el equipo de conekta, me ha funcionado correctamente oxxo pay, ahora si actualiza los pedidos en prestashop... pero aún sigue el problema de las tarjetas, espero lo puedan solucionar...

saludos

**Comment by edenriquez** [comment]
@ohlalo10 gracias por hacernos saber que hay un bug en el modulo de tarjeta, voy a hacer las pruebas entre hoy y el viernes para solucionarlo, solo una ultima pregunta, tienes prestashop 1.7.3 cierto ?

**Comment by edenriquez** [comment]
@ohlalo10 podrías mandarme un correo a eenriquez@conekta.com  para revisar a fondo tu caso, hice la prueba en prestashop 1.7.3 y fue exitosa la compra, gracias!

**Comment by ohlalo10** [comment]
Que tal @eduardoconekta , ya te mande un inbox, te comento q efectivamente tengo instalada la versiom 1.7.3.0 de prestashop, saludos

**Comment by HumbertoSa3nz** [comment]
Yo tengo prestashop 1.7.4.2 y no logro instalarlo, alguien tiene el mismo problema?

**Comment by edenriquez** [comment]
@HumbertoSa3nz que problema tienes ?, seguiste los pasos de instalación del repo ? 
https://github.com/conekta/conekta_prestashop

**Comment by teksop** [comment]
Que tal @eduenriquez yo estoy instalando el modulo que tienes aqui y me sigue dando error al momento de verificar el webhook, por otro lado queria preguntarte por que si es normal que no salga en metodos de pago.

**Comment by edenriquez** [comment]
Que tal @teksop si no sale en metodos de pago es debido a que no se configuraron correctamente los settings, en que version de prestashop estas instalando el plugin ?, el error en el webhook es debido a que posiblemente ya esta registrado el webhook en tu admin de conekta, verifica si ya tienes dada de alta la url del webhook.

**Comment by teksop** [comment]
La estoy instalando en 1.7.5.1 y la elimine los webhook y lo hago de nuevo
y sigue saliendo igual.

Gracias por tu apoyo

**Comment by luisluna85** [comment]
Yo tambien tengo el mismo problema, no me cambia el estatus del pedido a pagado estoy usando prestashop 1.7.5.1, alguien ha encontrado alguna solucion?

**Comment by teksop** [comment]
No es compatible con esa versión y decidí cambiarme a openpay
