### ISSUE TITLE
Problemas con pagos

### ISSUE THREAD

**Issue by cguerrero** [conekta/conektaprestashop#52]
Al realizar un pago con distintas tarjetas simplemente regresa un error que dice "token", y hay que volver a ingresar los datos de la tarjeta hasta que pase, hay alguna forma de corregirlo???

**Comment by Janee** [comment]
Hola @cguerrero ¿puedes compartirnos mas detalle en soporte@conekta.io en conjunto con el correo de tu cuenta de Conekta?

**Comment by jerrydomm** [comment]
Me sale el mismo error en modo sandbox....
