### ISSUE TITLE
Error al pagar con tarjeta

### ISSUE THREAD

**Issue by AldoAlbert** [conekta/conektaprestashop#76]
Hola, estoy tratando de usar el pago con tarjeta de crédito, con pago en oxxo funciona bien pero cuando selecciono la tarjeta y meto los datos solo recarga la página y no cambia el estatus del carrito ni de la compra.

Para webhook uso: https://midominio/modules/conekta_prestashop/notification.php

**Comment by lu1s** [comment]
Hola,

Puedes compartir un poco más de detalles sobre el error? Screenshot, versión del plugin, versión de prestashop, versión de php y mysql, etc...

**Comment by AldoAlbert** [comment]
Claro, las versiones que estamos manejando son:

Versión de PrestaShop: 1.7.2.3
Versión de MySQL: 5.7.21
Versión PHP: 7.0.22
Versión de plugin: v1.1.0

Al hacer el pago, la página redirige al index y agrega el token de la tarjeta a la url pero no se hace la transacción. Estamos en modo de pruebas.

**Comment by lu1s** [comment]
Esa versión del plugin ya no está en mantenimiento. Podrías actualizar? La más reciente es v2.1.0.

**Comment by AldoAlbert** [comment]
Estaba revisando y al parecer me equivoqué de repo al dar de alta el issue. Según la documentación la versión compatible para prestashop es la del repo conekta_prestashop que es la que maneja la v1.1.0 y esta es compatible con Prestashop < v1.7

Lo siento.

**Comment by lu1s** [comment]
Perfecto entonces cierro el issue y si sale otra cosa lo manejamos en el otro repo ✌️. 
https://github.com/conekta/conekta_prestashop
