### ISSUE TITLE
Conekta 2.1.0 Prestashop 1.6.1.18

### ISSUE THREAD

**Issue by cristophersosa** [conekta/conektaprestashop#80]
Este módulo no se puede instalar en la versión de prestashop 1.6.1.18, hay otra versión de este modulo en el cual se pueda instalar en esa version de prestashop?

**Comment by mauroarcet** [comment]
Puedes encontrar nuestro plugin para Prestashop 1.6 aquí:
https://github.com/conekta/conektaprestashop
