### ISSUE TITLE
Errores muestran siempre uno.

### ISSUE THREAD

**Issue by devSamuel** [conekta/conektaprestashop#9]
Cada actualización de conekta en nuestro sitio de producción tenemos miedo de que truene el modulo.

Esta ultima actualización "estable",  haciendo pruebas siempre nos muestra mensajes de error como "1". Obviamente esto no le dice nada al cliente. 
Viendo el código actualizado creo saber que la linea es esta 
 $this->smarty->assign("message", Tools::getIsset("message"));

en especial esto "Tools::getIsset("message")"

Antes de esta actualización queríamos integrar spei, pero oo gran sorpresa nunca se actualizaba el cargo cuando el cliente  pagaba. Dado que en notification.php 
al principio, antes de hacer cualquier include  u operación estaba esta linea, 
if (!defined('_PS_VERSION_')) {
    exit;
}
por lo tanto nos dimos a la tarea de esperar a que acualizaran

Les pedimos por favor que desarrollen versiones estables en funcionalidad y mensajes.

**Comment by menriquemcm** [comment]
Yo tambien encontre el mismo error, la cosa simplemente es cambiar en el archivo modules/conektaprestashop/conektaprestashop.php la linea que dice:
$this->smarty->assign("message", Tools::getIsset("message"));
por:
$this->smarty->assign("message", Tools::getValue("message"));

**Comment by fruizg0302** [comment]
Quedó corregido con el lanzamiento de API 2.0
